In [36]:
import numpy as np

In [42]:
from sklearn.model_selection import KFold

In [43]:
X=["a", "b", "c", "d"]

In [44]:
kf=KFold(n_splits=2)

In [47]:
for train, test in kf.split(X):
    print("%s,%s"%(train,test))

[2 3],[0 1]
[0 1],[2 3]


SyntaxError: unexpected EOF while parsing (<ipython-input-40-184db1e6461b>, line 1)

In [65]:
import numpy as np
from sklearn.model_selection import KFold

X = ["a", "b", "c", "d"]
kf = KFold(n_splits=3)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[2 3] [0 1]
[0 1 3] [2]
[0 1 2] [3]


In [53]:
from sklearn.model_selection import StratifiedKFold

In [62]:
X=np.ones(10)
X

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
y=['0','0','0','0','0','1','1','1','1','1']

In [63]:
skf=StratifiedKFold(n_splits=2)

In [64]:
for train,test in skf.split(X,y):
    print("%s%s"%(train,test))

[3 4 8 9][0 1 2 5 6 7]
[0 1 2 5 6 7][3 4 8 9]
